# https://hub.docker.com/r/microsoft/devcontainers-javascript-node
# NOTE: --platform=linux/amd64 is required for Amplify Gen2 sandbox (CDK Docker bundling only supports AMD64)
FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/typescript-node:22-bullseye